# Generated by Django 4.2.10 on 2024-03-12 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninaApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cactus',
            new_name='Mate',
        ),
    ]
