# Generated by Django 4.2.10 on 2024-03-12 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ninaApp', '0002_rename_cactus_mate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mate',
        ),
        migrations.DeleteModel(
            name='Planta',
        ),
    ]
