# Generated by Django 4.2.10 on 2024-03-12 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninaApp', '0003_delete_mate_delete_planta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('tamaño', models.IntegerField()),
                ('descripcion', models.TextField(blank=True)),
                ('stock', models.BooleanField(default=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
