# Generated by Django 4.2.10 on 2024-03-12 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninaApp', '0004_mate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maceta',
            name='stock',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='mate',
            name='stock',
            field=models.IntegerField(),
        ),
    ]
