# Generated by Django 4.2.10 on 2024-03-12 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninaApp', '0005_alter_maceta_stock_alter_mate_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['nombre', 'apellido'], 'verbose_name': 'Cliente', 'verbose_name_plural': 'Clientes'},
        ),
        migrations.AlterModelOptions(
            name='maceta',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterModelOptions(
            name='mate',
            options={'ordering': ['nombre']},
        ),
        migrations.AlterField(
            model_name='maceta',
            name='descripcion',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
