# Generated by Django 4.2.10 on 2024-03-12 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ninaApp', '0006_alter_cliente_options_alter_maceta_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mate',
            name='descripcion',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
